### ISSUE TITLE
Remove trailing newline from strings.

### ISSUE THREAD

**Issue by jamestalmage** [tapjs/tap-parser#27]
I propose we strip trailing newline characters from the following event strings:

- `line` ([example](https://github.com/tapjs/tap-parser/blob/72b12df8e7dd90febda6abe9c9bf8dd712a1e640/test/fixtures/combined.json#L13-L16)
- `comment` ([example](https://github.com/tapjs/tap-parser/blob/72b12df8e7dd90febda6abe9c9bf8dd712a1e640/test/fixtures/comment-mid-diag-postplan.json#L6-L9))
- `extra` ([example](https://github.com/tapjs/tap-parser/blob/72b12df8e7dd90febda6abe9c9bf8dd712a1e640/test/fixtures/child-extra.json#L106-L109))

Also, in the case of `comment` events, I also think we should remove the leading `"# "` (hash plus one whitespace char).

**Comment by isaacs** [comment]
Removing these things means that you have to add them back in synthetically if you ever want the raw data.

Whenever I have parsers that nest, I invariably find myself in a position where I want to pass data up or down the hierarchy, so I tend to avoid that sort of trimming as a general rule.

It seems like an unnecessary breaking change.  Do you have a use case for it?

**Comment by isaacs** [comment]
(happy to reopen, just closing for now because it needs some additional justification before accepting)
