### ISSUE TITLE
Emit values even if they're 0

### ISSUE THREAD

**Issue by Jameskmonger** [tapjs/tap-parser#40]
I think we should emit `fail`, `todo` and `skip` on `complete` all the time, even if they're falsy.

That way it's easier to consume the event because you don't need to check for undefined when consuming it. It also makes the object schema a bit more consistent.

What do you guys think? @isaacs @sindresorhus @ljharb

**Comment by isaacs** [comment]
Seems reasonable to me.  I think the only reason they're emitted is to reduce noise when they're output in yaml by harnesses.  But that'd usually only happen on failure, so it's fine.

**Comment by Jameskmonger** [comment]
Great @isaacs 

Would be a lot easier if I could do this:

    parser.on("complete", results => {
        let totals = {
            pass: results.pass,
            fail: results.pass,
            skip: results.skip + results.todo
        };
    });

Rather than:

    parser.on("complete", results => {
        let totals = {
            pass: results.pass,
            fail: results.pass || 0,
            skip: (results.skip || 0) + (results.todo || 0)
        };
    });

**Comment by isaacs** [comment]
Agreed!  Patch welcome.  Should be pretty straightforward.

**Comment by Jameskmonger** [comment]
@isaacs this has been submitted for PR in #44

**Comment by Jameskmonger** [comment]
Closed by #44, thanks @isaacs
