### ISSUE TITLE
looking for use case example - consuming stdout / stderr streams from child process

### ISSUE THREAD

**Issue by ORESoftware** [tapjs/tap-parser#47]
hello @isaacs and co

basically looking to do something like this:

```js
const parser = require('tap-parser');
const cp = require('child_process');
const n = cp.spawn('python',['foo.py']);

const dest = n.stdout.pipe(parser());

dest.on('pass', function(){
   console.log('test passed');
});

dest.on('fail', function(){
   console.log('test failed');
});

```

is a streaming usage like the one above possible with this module?
I would like print/use the results as they come in, in a streaming fashion.

**Comment by isaacs** [comment]
https://github.com/tapjs/tap-parser#ponassert-function-assert-

```js
dest.on('assert', function (testpoint) {
  if (testpoint.ok) {
    // it is ok
  } else {
    // it is not ok
  }
})
```

**Comment by isaacs** [comment]
(Note that you can also run non-JS programs with [tap](http://node-tap.org) if they are executable and have a shebang line.)

**Comment by ORESoftware** [comment]
got it thanks, I was expecting something like

`dest.on('pass')` or `dest.on('fail')` but I guess I don't know TAP that well.

**Comment by ORESoftware** [comment]
one more question @isaacs - you ever seen any problems with parsing streams with data chunks that don't represent the complete line, etc? I assume you handle that as best you can. I feel like it's mostly up to programming language's std libs to get that right.

**Comment by isaacs** [comment]
It's fine.  You can write it all at once, or one byte at a time, or anything in between.  https://github.com/tapjs/tap-parser/blob/master/index.js#L343-L351

**Comment by ORESoftware** [comment]
thanks, one more question for you maestro - I assume all tap output should be written to stdout - there's not reason tap output would ever be written to stderr. Is that assumption correct?

**Comment by isaacs** [comment]
This is really way off topic for this repo.

From tap-parser's point of view, you put text into it, and it spits out events based on that text being a TAP stream.  It doesn't care if it's stdout, stderr, a file you're reading, an HTTP connection, etc.  It's just text -> events.

From _[node-tap](http://npm.im/tap)_'s point of view, yeah, it spawns child processes that output TAP data to stdout, that's how it works.  But you don't have to do it that way, and the parser has no opinions about where its data comes from.

**Comment by the1mills** [comment]
Well ultimately Isaac my question was - by convention all tap output from child processes should come via stdout and none from stderr? Is that generally true? Not too off topic is it?

**Comment by isaacs** [comment]
@the1mills This repo is for the parser.  The parser doesn't care where the data comes from.

By convention, yes, most tap frameworks write test output to stdout.
