### ISSUE TITLE
Passed tests

### ISSUE THREAD

**Issue by epoberezkin** [tapjs/tap-parser#51]
Failed tests are included in the parsed output in 'failures' field.

Can we add 'successes' field to include all passed tests with their objects?

**Comment by isaacs** [comment]
Why not just listen to the `assert` event?  What's the use case for this?

**Comment by epoberezkin** [comment]
> Why not just listen to the assert event?

It's just seems easier to process in callback, once all results are parsed. It's possible for failures but not for successes

> What's the use case for this?

Whenever test results are used to maintain some state. In my case, failure creates an issue, success closes an issue (in [tap-github-issues](https://github.com/MailOnline/tap-github-issues) package)

**Comment by isaacs** [comment]
@epoberezkin Thanks!  That does make sense.  You could definitely do this by acting on each event as it comes in, but you'd probably have to switch from a yield-based system to a async/await type deal.  I can see how it's easier to just wait for it all to be done in this case.

**Comment by isaacs** [comment]
Landed on latest release.  Thanks!

**Comment by epoberezkin** [comment]
@isaacs thank you!

**Comment by ORESoftware** [comment]
mucho bueno 👍
