### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [tapjs/tap-parser#63]
Hi, what is the current status of this project? Is it still maintained?

**Comment by ORESoftware** [comment]
it's maintained, maybe not as much in the last 18 months, but it's used by tapjs so it's being used heavily

**Comment by coreyfarrell** [comment]
Definitely maintained and critical to tapjs.  In addition to `t.spawn()` using this to interpret output from the testing of the child process this module is core to the process of producing nice output from tap tests (instead of raw tap output).

**Comment by DanielRuf** [comment]
Thanks for the clarification.
